name: eset
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  context_plus: ^4.1.3

  image_ops: ^0.0.1
  compression_rs: ^0.0.1
  file_picker: ^8.1.4
  xml: ^6.5.0
  file_system_access:
    path: /Users/juanmanuelcastillo/Desktop/flutter/file_system_access
  json_form:
    git: https://github.com/juancastillo0/json_form.git
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - packages/file_system_access/assets/file_persistence.js
